# Generated by Django 5.1.5 on 2025-01-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='account_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='risk_tolerance',
        ),
    ]
