version: "3.8"

services:
  app:
    build: .
    container_name: fullstack_app
    ports:
      - "8000:8000" # Django API
      - "3000:3000" # Next.js frontend
      - DATABASE_URL=postgresql://postgres:kentud-0tasWy-kipqen@db.qwswrmbrmmpzmetdncxg.supabase.co:5432/postgres
    volumes:
      - .:/app
    restart: always
