version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=your_supabase_database_url
      - SECRET_KEY=your_django_secret_key
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: ["serve", "-s", "out", "-l", "3000"]
    volumes:
      - ./frontend:/app/frontend
