# Generated by Django 5.1.5 on 2025-01-26 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hedgefunds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=20)),
                ('as_of_date', models.DateField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_metrics', to='hedgefunds.portfolio')),
            ],
        ),
    ]
