# Generated by Django 5.1.5 on 2025-01-26 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hedgefunds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('instrument_type', models.CharField(choices=[('STOCK', 'Stock'), ('BOND', 'Bond'), ('FUTURE', 'Future'), ('OPTION', 'Option'), ('CRYPTO', 'Cryptocurrency')], max_length=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('price', models.DecimalField(decimal_places=4, max_digits=20)),
                ('trade_date', models.DateField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.instrument')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='hedgefunds.portfolio')),
            ],
        ),
    ]
